### PR TITLE
EE-77: fix routing of internal links to test environment

### PR DESCRIPTION
**Pull request by mtCarto**
Need confirmation of what routes should point to the test environment

### CODE REVIEW

**Comment by mtCarto** [comment]
Clarification this came up as I was accessing the test environment. Our confluence docs have 2 routes:
**internal:** https://esm-test.pathfinder.gov.bc.ca/admin/
**external:** https://test.projects.eao.gov.bc.ca/admin/

If you use the internal link the admin UI will make requests to the prod api as the _**esm-test**_ url is not in the case statement for the test routes

**Comment by MaxWardle** [comment]
Maybe we shouldn't default to the prod environment either, just to be safe? It does that on public too: https://github.com/bcgov/eagle-public/blob/c0987e4c5c23126e297a2b982cdb2a85eb92c9e1/src/app/services/api.ts#L68

**Comment by mtCarto** [comment]
Yeah we probably should, created [EE-145](https://bcmines.atlassian.net/browse/EE-145) to change defaults

**Comment by mtCarto** [comment]
Opened #192 to update default api route on admin
&
on eagle-public [PR-85](https://github.com/bcgov/eagle-public/pull/85)

**Comment by marklise** [comment]
I'm thinking we should unify the test environment - we don't need two routes doing the exact same thing.  Two options:
1) purge test.*, and use esm-test.*  Benefit is one less ssl cert to manage, and needs to be in coordination with removal of siteminder RP. (Tagging @ActionAnalytics )
2) purge esm-test.*, and use existing.  Benefit less work.

**Pull request merged**
